//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.BAPLN.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_CursoLectivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_CursoLectivo()
        {
            this.HIS_HistorialAcademico = new HashSet<HIS_HistorialAcademico>();
            this.LIS_Instituciones = new HashSet<LIS_Instituciones>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public bool Activa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HIS_HistorialAcademico> HIS_HistorialAcademico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIS_Instituciones> LIS_Instituciones { get; set; }
    }
}
