//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.BAPLN.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_Beca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_Beca()
        {
            this.LIS_BecaEstudiante = new HashSet<LIS_BecaEstudiante>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public int Id_TipoBeca { get; set; }
        public decimal MontoTotal { get; set; }
        public decimal MontoCuota { get; set; }
        public short CantidadCuotas { get; set; }
        public bool Activa { get; set; }
    
        public virtual CAT_TipoBeca CAT_TipoBeca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIS_BecaEstudiante> LIS_BecaEstudiante { get; set; }
    }
}
