//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.BAPLN.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_HistorialAcademico
    {
        public int Id { get; set; }
        public int Id_Estudiante { get; set; }
        public int Id_Materia { get; set; }
        public int Id_Periodo { get; set; }
        public int Id_Nivel { get; set; }
        public short Nota { get; set; }
        public int Id_CursoLectivo { get; set; }
        public int Id_Institucion { get; set; }
    
        public virtual CAT_CursoLectivo CAT_CursoLectivo { get; set; }
        public virtual CAT_Materia CAT_Materia { get; set; }
        public virtual CAT_Nivel CAT_Nivel { get; set; }
        public virtual CAT_Periodo CAT_Periodo { get; set; }
        public virtual LIS_Estudiante LIS_Estudiante { get; set; }
        public virtual LIS_Instituciones LIS_Instituciones { get; set; }
    }
}
