//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.BAPLN.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIS_Estudiante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LIS_Estudiante()
        {
            this.HIS_HistorialAcademico = new HashSet<HIS_HistorialAcademico>();
            this.LIS_BecaEstudiante = new HashSet<LIS_BecaEstudiante>();
            this.LIS_Responsable = new HashSet<LIS_Responsable>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Carne { get; set; }
        public string Cedula { get; set; }
        public string Padre { get; set; }
        public string Madre { get; set; }
        public string TelefonoLocal { get; set; }
        public string TelefonoMovil { get; set; }
        public string Fotografia { get; set; }
        public string Direccion { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public int Id_Nacionalidad { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> Id_Institucion { get; set; }
    
        public virtual CAT_Nacionalidad CAT_Nacionalidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HIS_HistorialAcademico> HIS_HistorialAcademico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIS_BecaEstudiante> LIS_BecaEstudiante { get; set; }
        public virtual LIS_Instituciones LIS_Instituciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIS_Responsable> LIS_Responsable { get; set; }
    }
}
