//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.BAPLN.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIS_Donador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LIS_Donador()
        {
            this.HIS_HistorialAportes = new HashSet<HIS_HistorialAportes>();
            this.LIS_CuotasBeca = new HashSet<LIS_CuotasBeca>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Email { get; set; }
        public string TelefonoLocal { get; set; }
        public string TelefonoMovil { get; set; }
        public int Id_Periodicidad { get; set; }
        public decimal MontoAporte { get; set; }
        public int Id_Nacionalidad { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public bool Activo { get; set; }
    
        public virtual CAT_Nacionalidad CAT_Nacionalidad { get; set; }
        public virtual CAT_PeriodicidadPago CAT_PeriodicidadPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HIS_HistorialAportes> HIS_HistorialAportes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIS_CuotasBeca> LIS_CuotasBeca { get; set; }
    }
}
