//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.BAPLN.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIS_BecaEstudiante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LIS_BecaEstudiante()
        {
            this.LIS_CuotasBeca = new HashSet<LIS_CuotasBeca>();
        }
    
        public int Id { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFinal { get; set; }
        public int Id_Estudiante { get; set; }
        public int Id_Beca { get; set; }
        public bool Activa { get; set; }
        public Nullable<decimal> MontoTotal { get; set; }
        public Nullable<decimal> MontoCuota { get; set; }
        public Nullable<short> CantidadCuotas { get; set; }
    
        public virtual CAT_Beca CAT_Beca { get; set; }
        public virtual LIS_Estudiante LIS_Estudiante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIS_CuotasBeca> LIS_CuotasBeca { get; set; }
    }
}
