//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.BAPLN.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIS_AporteCuota
    {
        public int Id { get; set; }
        public Nullable<int> Id_Cuota { get; set; }
        public Nullable<int> Id_Aporte { get; set; }
    
        public virtual HIS_HistorialAportes HIS_HistorialAportes { get; set; }
        public virtual LIS_CuotasBeca LIS_CuotasBeca { get; set; }
    }
}
