//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.BAPLN.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIS_Responsable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LIS_Responsable()
        {
            this.LIS_Estudiante = new HashSet<LIS_Estudiante>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Cedula { get; set; }
        public string Telefono { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Direccion { get; set; }
        public string Email { get; set; }
        public string Trabajo { get; set; }
        public Nullable<decimal> IngresoMensual { get; set; }
        public string Oficio { get; set; }
        public string Escolaridad { get; set; }
        public string Conocimientos { get; set; }
        public Nullable<int> Id_EstadoCivil { get; set; }
        public Nullable<int> Id_Nacionalidad { get; set; }
        public Nullable<int> Id_TipoResponsable { get; set; }
    
        public virtual CAT_EstadoCivil CAT_EstadoCivil { get; set; }
        public virtual CAT_Nacionalidad CAT_Nacionalidad { get; set; }
        public virtual CAT_TipoResponsable CAT_TipoResponsable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIS_Estudiante> LIS_Estudiante { get; set; }
    }
}
